version: '0.2b'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    ports:
      - "5000:5000"
    environment:
      - DEBUG=0
      - SECRET_KEY=46@a01os_&53es#5_q@*#s)wcci4vnwk-e^#11#yt=gm8c(c+v
      - ALLOWED_HOSTS=*