# Generated by Django 5.2 on 2025-05-24 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('mount', models.PositiveIntegerField(verbose_name='Monto')),
                ('abbreviation', models.CharField(max_length=255, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name': 'monto de paquete',
                'verbose_name_plural': 'montos de paquetes',
            },
        ),
        migrations.CreateModel(
            name='PackageTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('abbreviation', models.CharField(max_length=5, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name': 'tipo de paquete',
                'verbose_name_plural': 'tipos de paquetes',
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('value', models.TextField(verbose_name='Valor')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'parametro',
                'verbose_name_plural': 'parametros',
            },
        ),
        migrations.CreateModel(
            name='PaymentsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('abbreviation', models.CharField(max_length=5, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name': 'tipo de pago',
                'verbose_name_plural': 'tipos de pagos',
            },
        ),
        migrations.CreateModel(
            name='StatesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('abbreviation', models.CharField(max_length=5, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name': 'estado',
                'verbose_name_plural': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('tracking_number', models.CharField(editable=False, max_length=11, primary_key=True, serialize=False, verbose_name='Número de seguimiento')),
                ('qr_code', models.ImageField(upload_to='qrcodes/', verbose_name='Codigo QR')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('sender', models.CharField(max_length=50, verbose_name='Remitente')),
                ('recipient', models.CharField(max_length=50, verbose_name='Destinatario')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('envelope_amount', models.PositiveIntegerField(default=0, verbose_name='Importe de sobre')),
                ('package_pickup', models.BooleanField(verbose_name='Recogida de paquete')),
                ('total_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Importe total')),
                ('package_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packageprices', verbose_name='Importe de paquete')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packagetypes', verbose_name='Tipo de paquete')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paymentstypes', verbose_name='Tipo de pago')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.stateslist', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'envio',
                'verbose_name_plural': 'envios',
            },
        ),
    ]
